### ISSUE TITLE
[Custom Outside Objects] LLL

### ISSUE THREAD

**Issue by explodingp** [Spookybuddy/LC-Mods#12]
Do the custom objects spawn on modded moons?

**Comment by ZigzagAwaka** [comment]
Ive seen configs for some custom moons (synthesis, castlegrounds, egypt, bozoros) but not all my installed moons soooooo maybe it has only been tested on certain moons and its not working for all others? idk
Also its a bit unclear as to what these objects actually look like other than the readme pictures who does not show everything

**Comment by Spookybuddy** [comment]
The way the system finds custom moons is by locating all .lethalbundle files and seeing if there is X.lethalbundle and Xscene.lethalbundle. If you can provide some moons this is not working for I can test and see if I can fix it.

**Comment by ZigzagAwaka** [comment]
Well on top of my mind there is plenty, infernis, gratar, starlancermoons, espira, gordion saga moons etc
since they are using LLL i dont think its a loading issue but probably something else
I have like 15+ modded moons but only some are being detected thats strange

**Comment by ZigzagAwaka** [comment]
Well on top of my mind there is plenty, infernis, gratar, starlancermoons, espira, gordion saga moons etc
since they are using LLL i dont think its a loading issue but probably something else
I have like 15+ modded moons but only some are being detected thats strange

**Comment by Spookybuddy** [comment]
Update to fix this issue is now available. Check for any moons that are still not found and let me know. I'll close this thread in a few days if nothing comes up.

**Comment by ZigzagAwaka** [comment]
ok ill check soon

**Comment by ZigzagAwaka** [comment]
ok ill check soon

**Comment by ZigzagAwaka** [comment]
Ok so it seems better now but there is still some strange things happening
Some moons are installed with a mod bundle but this mod don't detect moons in the bundle, only the bundle itself, for example StarlancerMoons and VoxxMoons are detected but that's the mod and not the moons (these bundles contains 2 and 4 moons)
![image](https://github.com/user-attachments/assets/2d31b601-c43f-4d9e-862b-bf5ceac4a4c5)

Also other moons that are not detected : the gordion saga moons (in the GordionSaga bundle), secret labs, atlas abyss, espira, flicker (i assume all of demonmae's moons) but surely there is more

**Comment by Spookybuddy** [comment]
New update is available which is able to detect moons in bundles, as well as DemonMae's naming convention. All the moons you listed should work now, but please list any more moons that are not found in the config. 

The Bepin LogOutput lists the moons the mod finds, and should also list the moons LethalLevelLoader finds, so if you have too many moons installed you can easily attach the LogOutput instead. Just bootup Lethal Company real quick, join a save, and then quit and send that to keep the log short.

**Comment by ZigzagAwaka** [comment]
Yep thats again better now, but i still see 2 that are not detected : secret labs and atlas abyss
[LogOutput.log](https://github.com/user-attachments/files/18306845/LogOutput.log)

**Comment by Spookybuddy** [comment]
> Yep thats again better now, but i still see 2 that are not detected : secret labs and atlas abyss [LogOutput.log](https://github.com/user-attachments/files/18306845/LogOutput.log)

Fixed.

**Comment by ZigzagAwaka** [comment]
ok i think everything's good now, i will come back if i find any other issues
